services:
  postgres:
    image: postgres:16-alpine
    container_name: opoquiz_db
    environment:
      POSTGRES_DB: opoquiz
      POSTGRES_USER: opoquiz_user
      POSTGRES_PASSWORD: opoquiz_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./00_run_subdirs.sh:/docker-entrypoint-initdb.d/00_run_subdirs.sh:ro
      - ./migrations:/docker-entrypoint-initdb.d/1-migrations
      - ./seeds:/docker-entrypoint-initdb.d/2-seeds
      - ./sql:/docker-entrypoint-initdb.d/3-sql

volumes:
  postgres_data:
